In [2]:
import numpy as np

In [7]:
A = np.array([10, 20, 30])
B = np.array([2, 4, 3])

In [8]:
print(A + B)

[12 24 33]


In [9]:
print(A - B)

[ 8 16 27]


In [10]:
print(A * B)

[20 80 90]


In [12]:
print(A // B)

[ 5  5 10]


In [13]:
print(np.min(A))
print(np.max(A))
print(np.sum(A))
print(np.mean(A))

10
30
60
20.0


In [5]:
A = [1, 2, 3, 4, 5]
A[1:4]

[2, 3, 4]

In [17]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A[0, 0])
print(A[1, 2])

1
6


In [19]:
print(A[0, 1:3])
print(A[:, 1])
print(A[:, :2])

[2 3]
[2 5]
[[1 2]
 [4 5]]
